generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmComCity
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: city
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=name'
          - dm_com_country_id
          - dm_com_address_list
          - latitude
          - longitude
          - created_by
          - updated_by
        sort:
          - name
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
          - dm_com_country_id
          - latitude
          - longitude
          - created_by
          - updated_by
      form:
        display:
          NONE: [name, dm_com_country_id]
          Addresses: [dm_com_address_list]
          Others: [latitude, longitude, created_by, updated_by]
        class: DmComCityAdminForm
        fields: {  }
      edit: ~
      new: ~
