Commerce:
  Categories:
    Category:
      model: DmComCategory
      page: true
      name: Category|Categories
      admin: true
      front: true
      components:
        list:
          cache: true
        listInProduct:
          filters: [products]
          cache: true
        show:
          cache: true
  
  Products:
    Product:
      model: DmComProduct
      page: true
      name: Product|Products
      admin: true
      front: true
      components:
        listByCategory:
          filters: [category]
          cache: true
        listByManufacturer:
          filters: [manufacturers]
          cache: true
        listBySupplyer:
          filters: [supplyers]
          cache: true
        show: 
          cache: true
        showInCategory:
          filters: [categories]
          cache: true
    ProductDeclination:
      parent: Product
      model: DmComProductDeclination
      page: true
      name: Product Declination|Product Declinations
      admin: true
      front: true
      components:
        listByProduct:
          filters: [product]
          cache: true
        show: 
          cache: true
        showInProduct:
          filters: [product]
          cache: true
          
    Supplier:
      model: DmComSupplier
      page: true
      name: Supplier|Suppliers
      admin: true
      front: true
      components:
        list:
          cache: static
        show:
          cache: static
          
    Manufacturer:
      model: DmComManufacturer
      page: true
      name: Manufacturer|Manufacturers
      admin: true
      front: true
      components:
        list:
          cache: static
        show: 
          cache: static
          
  Product Definitions:
    ProductType:
      model: DmComProductType
      page: true
      name: Product Type|Product Types
      admin: true
      front: true
      components:
        list:
          cache: true
        show: 
          cache: true
    ProductCharacteristicType:
      model: DmComProductCharType
      page: false
      name: Product Characteristic Type|Product Characteristic Types
      admin: true
      front: true
      
    ProductCharacteristicTypeProperty:
      model: DmComProductCharTypeProperty
      page: false
      name: Product Characteristic Type Property|Product Characteristic Type Properties
      admin: true
      front: true
    ProductCharacteristicTypePropertyType:
      model: DmComProductCharTypePropertyType
      page: false
      name: Product Characteristic Type Property Type|Product Characteristic Type Property Types
      admin: true
      front: true
  
  Locations:
    Country:
      model: DmComCountry
      page: false
      name: Country|Countries
      admin: true
      
    City:
      model: DmComCity
      page: false
      name: City|Cities
      admin: true
      front: true
      components:
        list: 
          cache: true
        show: 
          cache: true
            
    Address:
      model: DmComAddress
      page: false
      name: Address|Addresses
      admin: true
      front: true
      components:
        list:
          cache: true
        show:
          cache: true
          
    StreetType:
      model: DmComStreetType
      page: false
      name: Street Type|Street Types
      admin: true
      front: false
      
    BuildingFloor:
      model: DmComBuildingFloor
      page: false
      name: Building Floor|Building Floors
      admin: true
      front: false
    
    
      
              