generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmComBuildingFloor
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: building_floor
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=name'
          - dm_com_address_list
          - alias
          - created_by
          - updated_by
        sort:
          - name
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
          - alias
          - created_by
          - updated_by
      form:
        display:
          NONE: [name]
          Addresses: [dm_com_address_list]
          Others: [alias, created_by, updated_by]
        class: DmComBuildingFloorAdminForm
        fields: {  }
      edit: ~
      new: ~
