generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmComCategory
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: category
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        products_list:
          label: Products
        dm_gallery: Gallery
        dm_ns_parent_id:
          label: 'Child of'
      list:
        display:
          - '=title'
          - _dm_ns_parent_id
          - created_by
          - updated_by
          - dm_gallery
          - products_list
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - title
          - dm_ns_parent_id
          - created_by
          - updated_by
      form:
        display:
          NONE: [title, created_by, updated_by]
          Hierarchy: [dm_ns_parent_id]
          Products: [products_list]
          Gallery: [dm_gallery]
        class: DmComCategoryAdminForm
        fields: {  }
      edit: ~
      new: ~
