<?php

/**
 * PluginDmComProductCharTypePropertyProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmComProductCharTypePropertyProductTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmComProductCharTypePropertyProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmComProductCharTypePropertyProduct');
    }
}