<?php

/**
 * PluginDmComProductCharTypeProperty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginDmComProductCharTypeProperty extends BaseDmComProductCharTypeProperty
{
    public function getWidget()
    {
        switch ($this->getType()) {
            case DmComProductCharTypePropertyTable::TYPE_FEATURE : {
                return new sfWidgetFormInputCheckbox();
                break;
            }
            default : {
                return new sfWidgetFormInput();
                break;
            }
        }
    }
    
}