generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmComSupplier
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: supplier
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        dm_com_product_list:
          label: Products
        dm_gallery: Gallery
        address_country:
          label: Country
        address_city:
          label: City
        address_code:
          label: Postcode
        address_street:
          label: Street
      list:
        display:
          - '=name'
          - created_by
          - updated_by
          - dm_gallery
          - products_list
          - website_url
        sort:
          - name
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
          - website_url
          - created_by
          - updated_by
      form:
        display:
          NONE: [name, website_url]
          Address: [ address_country, address_code, address_city, address_street]
          Products: [ products_list]
          Gallery: [dm_gallery]
        class: DmComSupplierAdminForm
        fields: {  }
      edit: ~
      new: ~
