generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmComAddress
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: address
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=id'
          - dm_com_city_id
          - dm_com_street_type_id
          - dm_com_building_floor_id
          - created_by
          - updated_by
          - street_name
          - street_number
          - building
          - latitude
          - longitude
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - id
          - dm_com_city_id
          - dm_com_street_type_id
          - street_name
          - street_number
          - building
          - dm_com_building_floor_id
          - created_by
          - updated_by
          - latitude
          - longitude
      form:
        display:
          NONE: [dm_com_city_id, dm_com_street_type_id, dm_com_building_floor_id, created_by, updated_by]
          Others: [street_name, street_number, building, latitude, longitude]
        class: DmComAddressAdminForm
        fields: {  }
      edit: ~
      new: ~
