generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmComStreetType
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: street_type
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - '=title'
          - dm_com_address_list
          - created_by
          - updated_by
        sort:
          - title
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - title
          - created_by
          - updated_by
      form:
        display:
          NONE: [title]
          Addresses: [dm_com_address_list]
          Others: [created_by, updated_by]
        class: DmComStreetTypeAdminForm
        fields: {  }
      edit: ~
      new: ~
