DmComAddress:
  actAs:
    DmVersionable: ~
    Dmblameable: ~
    Geographical: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    dm_com_city_id:
      type: integer(11)
      notnull: true
    dm_com_street_type_id:
      type: integer(11)
      notnull: true
    street_name:
      type: string(255)
      notnull: true
    street_number:
      type: integer(4)
      notnull: false
    building:
      type: string(255)
      notnull: true
    dm_com_building_floor_id:
      type: integer(11)
  relations:
    city: 
      class: DmComCity
      type: one
      foreignType: many
      local: dm_com_city_id
      foreign: id
    streetType:
      class: DmComStreetType
      type: one
      foreignType: many
      local: dm_com_street_type_id
      foreign: id
    floor:
      class: DmComBuildingFloor
      type: one
      foreignType: many
      local: dm_com_building_floor_id
      foreign: id
      
DmComBuildingFloor:
  actAs:
    I18n:
      fields: [name, alias]
      length: 5
      actAs:
        DmVersionable: ~
        Dmblameable: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
    alias: 
      type: string(255)
      notnull: false


DmComCity:
  actAs:
    I18n:
      fields: [name]
      length: 5
      actAs:
        DmVersionable: ~
        Dmblameable: ~
    Geographical: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
    dm_com_country_id:
      type: integer(11)
      notnull: true
  relations:
    country:
      class: DmComCountry
      type: one
      foreignType: one
      local: dm_com_country_id
      foreign: id
      
DmComCountry:
  actAs:
    I18n:
      fields: [name]
      length: 5
      actAs: 
        DmVersionable: ~
        Dmblameable: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
  
DmComStreetType:
  actAs:
    I18n:
      fields: [title]
      length: 5
      actAs:
        DmVersionable: ~
        Dmblameable: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    title: 
      type: string(255)
      notnull: true
