DmCommerceAddress:
  actAs:
    DmVersionable: ~
    Dmblameable: ~
    Geographical: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    dm_commerce_city_id:
      type: integer(11)
      notnull: true
    dm_commerce_street_type_id:
      type: integer(11)
      notnull: true
    street_name:
      type: string(255)
      notnull: true
    street_number:
      type: integer(4)
      notnull: false
    building:
      type: string(255)
      notnull: true
    dm_commerce_building_floor_id:
      type: integer(11)
  relations:
    city: 
      class: DmCommerceCity
      type: one
      foreignType: many
      local: dm_commerce_city_id
      foreign: id
    streetType:
      class: DmCommerceStreetType
      type: one
      foreignType: many
      local: dm_commerce_street_type_id
      foreign: id
    floor:
      class: DmCommerceBuildingFloor
      type: one
      foreignType: many
      local: dm_commerce_building_floor_id
      foreign: id
      
DmCommerceBuildingFloor:
  actAs:
    I18n:
      fields: [name, alias]
      length: 5
      actAs:
        DmVersionable: ~
        Dmblameable: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
    alias: 
      type: string(255)
      notnull: false


DmCommerceCity:
  actAs:
    I18n:
      fields: [name]
      length: 5
      actAs:
        DmVersionable: ~
        Dmblameable: ~
    Geographical: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
    dm_commerce_country_id:
      type: integer(11)
      notnull: true
  relations:
    country:
      class: DmCommerceCountry
      type: one
      foreignType: one
      local: dm_commerce_country_id
      foreign: id
      
DmCommerceCountry:
  actAs:
    I18n:
      fields: [name]
      length: 5
      actAs: 
        DmVersionable: ~
        Dmblameable: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
  
DmCommerceStreetType:
  actAs:
    I18n:
      fields: [title]
      length: 5
      actAs:
        DmVersionable: ~
        Dmblameable: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    title: 
      type: string(255)
      notnull: true
