DmComSupplier:
  actAs:
    DmVersionable: ~
    Dmblameable: ~
    DmGallery: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
    address_country:
      type: string(255)
    address_code:
      type: string(255)
    address_city:
      type: string(255)
    address_street:
      type: string(255)
    website_url: 
      type: string(255)
  relations:
    products:
      class: DmComProduct
      type: many
      foreignType: many
      foreignAlias: manufacturer
      refClass: DmComSupplierProduct
      
DmComSupplierProduct:
  actAs:
    DmVersionable: ~
    Dmblameable: ~
  columns:
    dm_com_product_id:
      type: integer(11)
    dm_com_supplier_id:
      type: integer(11)
  relations:
    product:
      class: DmComProduct
      type: one
      foreignType: many
      foreign: id
      local: dm_com_product_id
    supplyer:
      class: DmComSupplier
      type: one
      foreignType: many
      foreign: id
      local: dm_com_supplier_id    