DmComManufacturer:
  actAs:
    DmVersionable: ~
    Dmblameable: ~
    DmGallery: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
    website_url: 
      type: string(255)
    dm_com_address_id:
      type: integer(11)
      notnull: true
  relations:
    products:
      class: DmComProduct
      type: many
      foreignType: one
      foreignAlias: manufacturer
      foreign: dm_com_manufacturer_id
      local: id
      