DmComProductType:
  actAs: 
    I18n:
      fields: [name]
      length: 5
      actAs:
        DmVersionable: ~
        Dmblameable: ~
  columns: 
    id:
      type: integer(11)
      primary: true
      autoincrement: true 
    name:
      type: string(255)
      notnull: true
  relations:
    characteristicTypes:
      class: DmComProductCharacteristicType
      refClass: DmComProductTypeProductCharacteristicType
      type: many
