DmComSupplier:
  actAs:
    DmVersionable: ~
    Dmblameable: ~
    DmGallery: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
    dm_com_address_id:
      type: integer(11)
      notnull: true
    website_url: 
      type: string(255)
  relations:
    products:
      class: DmComProduct
      type: many
      foreignType: many
      foreignAlias: manufacturer
    address:
      class: DmComAddress
      type: one
      foreignType: one
      local: dm_com_address_id
      foreign: id
      
DmComSupplierProduct:
  actAs:
    DmVersionable: ~
    Dmblameable: ~
  columns:
    dm_com_product_id:
      type: integer(11)
    dm_com_supplier_id:
      type: integer(11)
  relations:
    product:
      class: DmComProduct
      type: one
      foreignType: many
      foreign: id
      local: dm_com_product_id
    supplyer:
      class: DmComSupplier
      type: one
      foreignType: many
      foreign: id
      local: dm_com_supplier_id    