DmComCategory:
  actAs:
    DmSortable:  
    NestedSet: 
      hasManyRoots: true
    I18n:
      fields: [title, description]
      length: 5
      actAs:
        DmVersionable: ~
        Dmblameable: ~
    Dmblameable: ~
    DmVersionable: ~ 
    DmGallery: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    title: 
      type: string(255)
    description: 
      type: string()
  relations:
    products:
      class: DmComProduct
      refClass: DmComCategoryProduct
      type: many
      
DmComCategoryProduct:
  actAs:
    DmVersionable: ~
    Dmblameable: ~
  columns:
    dm_com_category_id:
      type: integer(11)
    dm_com_product_id:
      type: integer(11)
  relations:
    category:
      class: DmComCategory
      type: one
      foreignType: many
      foreign: id
      local: dm_com_category_id
    product:
      class: DmComProduct
      type: one
      foreignType: many
      foreign: id
      local: dm_com_product_id
      
