DmComProductCharType:
  actAs:
    I18n:
      fields: [name, description]
      length: 5
      actAs:
        DmVersionable:
        Dmblameable:
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
  relations:
    productTypes:
      class: DmComProductType
      refClass: DmComProductTypeProductCharType
      type: many
    properties:
      class: DmComProductCharTypeProperty
      type: many
      foreignType: one
      local: id
      foreign: dm_com_product_char_type_id
      foreignAlias: CharType
   
DmComProductCharTypeProperty:
  actAs:
    DmSortable:
    I18n:
      fields: [name]
      length: 5
      actAs:
        DmVersionable:
        Dmblameable:
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    dm_com_product_char_type_id: 
      type: integer(11)
      notnull: true
    type:
      type: integer(2)
      notnull: true
  relations:
    productCharType:
      class: DmComProductCharType
      type: one
      foreignType: many
      local: dm_com_product_char_type_id
      foreign: id
    values:
      class: DmComProductCharTypePropertyProduct
      type: many
      foreignType: one
      foreign: dm_com_product_char_type_propery_id
      local: id
      
# Values class Product Char Type Property <-> Product
DmComProductCharTypePropertyProduct: 
  actAs:
    DmVersionable:
    Dmblameable:  
  columns:
    dm_com_product_char_type_propery_id:
      type: integer(11)
    dm_com_product_id:
      type: integer(11)
    value:  string(255)
  relations:
    product:
      class: DmComProduct
      type: one
      foreignType: many
      foreignAlias: Properties
      local: dm_com_product_id
      foreign: id
    property:
      class: DmComProductCharTypeProperty
      type: one
      foreignType: many
      local: dm_com_product_char_type_propery_id
      foreign: id
          
# Ref class Product Characteristic Type <-> Product Type
DmComProductTypeProductCharType:
  actAs:
    DmVersionable:
    Dmblameable:
  columns:
    dm_com_product_type_id:
      type: integer(11)
    dm_com_product_char_type_id:
      type: integer(11)
  relations:
    productType:
      class: DmComProductType
      type: one
      foreignType: many
      foreign: id
      local: dm_com_product_type_id
    CharType:
      class: DmComProductCharType
      type: one
      foreignType: many
      foreign: id
      local: dm_com_product_char_type_id

