DmCommerceManufacturer:
  actAs:
    DmVersionable: ~
    Dmblameable: ~
    DmGallery: ~
  columns:
    id:
      type: integer(11)
      primary: true
      autoincrement: true
    name: 
      type: string(255)
      notnull: true
    website_url: 
      type: string(255)
    dm_commerce_address_id:
      type: integer(11)
      notnull: true
  relations:
    products:
      class: DmCommerceProduct
      type: many
      foreignType: one
      foreignAlias: manufacturer
      foreign: dm_commerce_manufacturer_id
      local: id
    address:
      class: DmCommerceAddress
      type: one
      foreignType: one
      local: dm_commerce_address_id
      foreign: id
      