generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmComProduct
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: product
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        categories_list:
          label: Categories
        suppliers_list:
          label: Suppliers
        dm_gallery: Gallery
      list:
        display:
          - '=name'
          - dm_com_product_type_id
          - dm_com_manufacturer_id
          - created_by
          - updated_by
          - dm_gallery
          - declinations_list
          - categories_list
          - suppliers_list
          - description
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - name
          - dm_com_manufacturer_id
          - dm_com_product_type_id
          - created_by
          - updated_by
          - description
      form:
        display:
          NONE: [name, dm_com_product_type_id, dm_com_manufacturer_id, created_by, updated_by]
          Categories: [categories_list]
          Suppliers: [suppliers_list]
          'Product Declinations': [declinations_list]
          Gallery: [dm_gallery]
          Others: [description]
        class: DmComProductAdminForm
        fields: {  }
      edit: ~
      new: ~
